import Head from 'next/head'
import styles from '@/styles/Home.module.scss'
import { CarPokemon } from '@/components/pokemon-list'
import { PesquisaPokemon } from '@/components/search-pokemon/pesquisa_Pokemon'

export default function Home() {
  return (
    <>
      <Head>
        <title>Word-pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Word Pokemon</h1>

        <PesquisaPokemon />

        <CarPokemon />
      </main>
    </>
  )
}
